# Basic Information
title: Rui Shi (史睿)
display_name: Rui Shi
position: M.S. Student
affiliation: Shanghai Jiao Tong University
email: shi-rui (at) sjtu.edu.cn

# Search Engine Optimization (SEO)
keywords: Rui Shi, computer vision, 3D vision, medical image analysis
canonical: https://threesrr.github.io/
description: 

# The option is used to enable the MPI Informatics template.
enable_mpi_logo: false

# The option is used to show the last update time.
enable_last_update: false

# Links
google_scholar: https://scholar.google.com/citations?user=hAzJfKwAAAAJ
# cv_link: assets/files/curriculum_vitae.pdf
github_link: https://github.com/ThreeSRR
# linkedin: https://www.linkedin.com/
# twitter: https://twitter.com/

# Images
avatar: ./assets/img/avatar.png
# favicon: ./assets/img/favicon.png
# favicon_dark: ./assets/img/favicon-dark.png

# Footnotes
enable_footnote: true

# The following files will be removed from the generated website.
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENSE
  - CNAME
